name: release

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    name: release

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        node-version: [24]

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release
